-- NOBI 动漫 V2: privacy-conscious page views, persistent image likes and admin metrics.
-- Production execution is blocked until supabase/production_preflight.sql has been reviewed.
begin;

-- Fail closed if the production authorization/uniqueness preconditions are not met.
-- The read-only preflight remains mandatory because policies and function owners require human review.
do $$
declare
  required_unique_column record;
begin
  if not exists (
    select 1
    from pg_catalog.pg_class as class
    where class.oid = 'public.users'::regclass
      and class.relrowsecurity
  ) then
    raise exception 'Production preflight failed: public.users must have RLS enabled';
  end if;

  if pg_catalog.has_column_privilege('anon', 'public.users', 'is_admin', 'UPDATE')
    or pg_catalog.has_column_privilege('authenticated', 'public.users', 'is_admin', 'UPDATE')
  then
    raise exception 'Production preflight failed: anon/authenticated must not be able to update users.is_admin';
  end if;

  for required_unique_column in
    select *
    from (values
      ('public.users', 'id'),
      ('public.content_management', 'id'),
      ('public.site_config', 'section')
    ) as required(table_name, column_name)
  loop
    if not exists (
      select 1
      from pg_catalog.pg_index as index_row
      join pg_catalog.pg_attribute as attribute
        on attribute.attrelid = index_row.indrelid
        and index_row.indkey[0] = attribute.attnum
      where index_row.indrelid = required_unique_column.table_name::regclass
        and index_row.indisunique
        and index_row.indnkeyatts = 1
        and index_row.indpred is null
        and index_row.indexprs is null
        and attribute.attname = required_unique_column.column_name
    ) then
      raise exception 'Production preflight failed: %.% must have a single-column PRIMARY KEY or UNIQUE index',
        required_unique_column.table_name,
        required_unique_column.column_name;
    end if;
  end loop;

  if exists (
    select 1
    from public.site_config as config
    group by config.section
    having count(*) > 1
  ) then
    raise exception 'Production preflight failed: public.site_config contains duplicate section values';
  end if;
end
$$;

-- Align admin checks with the deployed users table used by admin.html.
-- The production preflight must prove that ordinary users cannot modify users.is_admin.
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = pg_catalog, public
as $$
  select coalesce((select users.is_admin from public.users as users where users.id = auth.uid()), false)
$$;
revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

create table if not exists public.page_views (
  id bigint generated by default as identity primary key,
  session_id uuid not null,
  visitor_id uuid not null,
  page_path text not null,
  viewed_at timestamptz not null default now(),
  viewed_on date not null default ((now() at time zone 'Asia/Shanghai')::date),
  constraint page_views_page_path_check
    check (char_length(page_path) between 1 and 200 and page_path like '/%')
);

-- IF NOT EXISTS must not silently accept a table created with an incompatible shape.
do $$
declare
  expected_column record;
begin
  for expected_column in
    select *
    from (values
      ('id', 'bigint', true),
      ('session_id', 'uuid', true),
      ('visitor_id', 'uuid', true),
      ('page_path', 'text', true),
      ('viewed_at', 'timestamp with time zone', true),
      ('viewed_on', 'date', true)
    ) as expected(name, data_type, required_not_null)
  loop
    if not exists (
      select 1
      from pg_catalog.pg_attribute as attribute
      where attribute.attrelid = 'public.page_views'::regclass
        and attribute.attname = expected_column.name
        and pg_catalog.format_type(attribute.atttypid, attribute.atttypmod) = expected_column.data_type
        and attribute.attnotnull = expected_column.required_not_null
        and not attribute.attisdropped
    ) then
      raise exception 'public.page_views has an incompatible % column', expected_column.name;
    end if;
  end loop;

  if not exists (
    select 1
    from pg_catalog.pg_constraint as constraint_row
    where constraint_row.conrelid = 'public.page_views'::regclass
      and constraint_row.contype = 'p'
      and constraint_row.conkey = array[(
        select attribute.attnum
        from pg_catalog.pg_attribute as attribute
        where attribute.attrelid = 'public.page_views'::regclass and attribute.attname = 'id'
      )]::smallint[]
  ) then
    raise exception 'public.page_views must have id as its primary key';
  end if;

  if not exists (
    select 1
    from pg_catalog.pg_attribute as attribute
    where attribute.attrelid = 'public.page_views'::regclass
      and attribute.attname = 'id'
      and attribute.attidentity in ('a', 'd')
  ) then
    raise exception 'public.page_views.id must be an identity column';
  end if;

  if not exists (
    select 1
    from pg_catalog.pg_constraint as constraint_row
    where constraint_row.conrelid = 'public.page_views'::regclass
      and constraint_row.conname = 'page_views_page_path_check'
      and constraint_row.contype = 'c'
  ) then
    raise exception 'public.page_views is missing page_views_page_path_check';
  end if;
end
$$;

create index if not exists page_views_viewed_at_idx on public.page_views (viewed_at desc);
create index if not exists page_views_viewed_on_visitor_idx on public.page_views (viewed_on, visitor_id);
create index if not exists page_views_session_path_time_idx
  on public.page_views (session_id, page_path, viewed_at desc);

do $$
begin
  if not exists (
    select 1
    from pg_catalog.pg_index as index_row
    join pg_catalog.pg_class as index_class on index_class.oid = index_row.indexrelid
    where index_class.relnamespace = 'public'::regnamespace
      and index_class.relname = 'page_views_session_path_time_idx'
      and index_row.indrelid = 'public.page_views'::regclass
      and pg_catalog.pg_get_indexdef(index_row.indexrelid) like '%(session_id, page_path, viewed_at DESC)%'
  ) then
    raise exception 'page_views_session_path_time_idx has an incompatible definition';
  end if;
end
$$;

alter table public.page_views enable row level security;
revoke all on table public.page_views from anon, authenticated;

drop policy if exists "page views admin read" on public.page_views;
create policy "page views admin read"
on public.page_views
for select
to authenticated
using (public.is_admin());

create or replace function public.record_page_view(
  p_session_id uuid,
  p_visitor_id uuid,
  p_page_path text
)
returns void
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  normalized_page_path text;
begin
  if p_session_id is null or p_visitor_id is null then
    raise exception 'Anonymous identifiers are required';
  end if;
  if p_page_path is null or char_length(p_page_path) > 2048 then
    raise exception 'Invalid page path';
  end if;

  -- Page-view identity excludes query strings and fragments.
  normalized_page_path := split_part(split_part(btrim(p_page_path), '#', 1), '?', 1);
  if char_length(normalized_page_path) not between 1 and 200 or normalized_page_path not like '/%' then
    raise exception 'Invalid page path';
  end if;

  -- Serialize the complete five-second check/insert window for one session and page.
  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(p_session_id::text || E'\x1f' || normalized_page_path, 0)
  );

  if exists (
    select 1
    from public.page_views as views
    where views.session_id = p_session_id
      and views.page_path = normalized_page_path
      and views.viewed_at > pg_catalog.now() - interval '5 seconds'
  ) then
    return;
  end if;

  insert into public.page_views (session_id, visitor_id, page_path)
  values (p_session_id, p_visitor_id, normalized_page_path);
end;
$$;

revoke all on function public.record_page_view(uuid, uuid, text) from public;
grant execute on function public.record_page_view(uuid, uuid, text) to anon, authenticated;

-- A stable image identity is the normalized public Storage bucket/object path.
-- Hostnames, query strings and fragments are intentionally excluded.
create or replace function public.nobi_storage_image_key(p_url text)
returns text
language sql
immutable
strict
set search_path = pg_catalog
as $$
  with normalized as (
    select split_part(split_part(btrim(p_url), '#', 1), '?', 1) as url
  ), matched as (
    select regexp_match(
      normalized.url,
      '^https?://[^/]+/storage/v1/object/public/([^/]+)/(.+)$',
      'i'
    ) as parts
    from normalized
  )
  select case
    when matched.parts is null or btrim(matched.parts[2], '/') = '' then null
    else lower(matched.parts[1]) || '/' || btrim(matched.parts[2], '/')
  end
  from matched
$$;
revoke all on function public.nobi_storage_image_key(text) from public;

create table if not exists public.image_likes (
  id bigint generated by default as identity primary key,
  image_key text not null,
  content_id uuid not null,
  image_kind text not null,
  image_index integer not null default 0,
  user_id uuid,
  anonymous_id uuid,
  created_at timestamptz not null default now(),
  constraint image_likes_key_check
    check (char_length(image_key) between 3 and 2048 and image_key ~ '^[^/?#]+/.+$'),
  constraint image_likes_kind_check
    check (image_kind in ('banner', 'cover', 'detail')),
  constraint image_likes_index_check
    check (image_index >= 0),
  constraint image_likes_one_actor check (
    (user_id is not null and anonymous_id is null)
    or (user_id is null and anonymous_id is not null)
  ),
  constraint image_likes_content_fk
    foreign key (content_id) references public.content_management(id) on delete cascade,
  constraint image_likes_user_fk
    foreign key (user_id) references auth.users(id) on delete cascade
);

do $$
declare
  expected_column record;
begin
  for expected_column in
    select *
    from (values
      ('id', 'bigint', true),
      ('image_key', 'text', true),
      ('content_id', 'uuid', true),
      ('image_kind', 'text', true),
      ('image_index', 'integer', true),
      ('user_id', 'uuid', false),
      ('anonymous_id', 'uuid', false),
      ('created_at', 'timestamp with time zone', true)
    ) as expected(name, data_type, required_not_null)
  loop
    if not exists (
      select 1
      from pg_catalog.pg_attribute as attribute
      where attribute.attrelid = 'public.image_likes'::regclass
        and attribute.attname = expected_column.name
        and pg_catalog.format_type(attribute.atttypid, attribute.atttypmod) = expected_column.data_type
        and attribute.attnotnull = expected_column.required_not_null
        and not attribute.attisdropped
    ) then
      raise exception 'public.image_likes has an incompatible % column', expected_column.name;
    end if;
  end loop;

  if not exists (
    select 1
    from pg_catalog.pg_constraint as constraint_row
    where constraint_row.conrelid = 'public.image_likes'::regclass
      and constraint_row.contype = 'p'
      and constraint_row.conkey = array[(
        select attribute.attnum
        from pg_catalog.pg_attribute as attribute
        where attribute.attrelid = 'public.image_likes'::regclass and attribute.attname = 'id'
      )]::smallint[]
  ) then
    raise exception 'public.image_likes must have id as its primary key';
  end if;

  if not exists (
    select 1
    from pg_catalog.pg_attribute as attribute
    where attribute.attrelid = 'public.image_likes'::regclass
      and attribute.attname = 'id'
      and attribute.attidentity in ('a', 'd')
  ) then
    raise exception 'public.image_likes.id must be an identity column';
  end if;

  if (
    select count(*)
    from pg_catalog.pg_constraint as constraint_row
    where constraint_row.conrelid = 'public.image_likes'::regclass
      and constraint_row.conname = any(array[
        'image_likes_key_check',
        'image_likes_kind_check',
        'image_likes_index_check',
        'image_likes_one_actor',
        'image_likes_content_fk',
        'image_likes_user_fk'
      ])
      and (
        (constraint_row.conname in (
          'image_likes_key_check',
          'image_likes_kind_check',
          'image_likes_index_check',
          'image_likes_one_actor'
        ) and constraint_row.contype = 'c')
        or (
          constraint_row.conname = 'image_likes_content_fk'
          and constraint_row.contype = 'f'
          and constraint_row.confrelid = 'public.content_management'::regclass
          and constraint_row.confdeltype = 'c'
        )
        or (
          constraint_row.conname = 'image_likes_user_fk'
          and constraint_row.contype = 'f'
          and constraint_row.confrelid = 'auth.users'::regclass
          and constraint_row.confdeltype = 'c'
        )
      )
  ) <> 6 then
    raise exception 'public.image_likes is missing one or more required constraints';
  end if;
end
$$;

create unique index if not exists image_likes_user_unique_idx
  on public.image_likes (image_key, user_id)
  where user_id is not null;
create unique index if not exists image_likes_anonymous_unique_idx
  on public.image_likes (image_key, anonymous_id)
  where anonymous_id is not null;
create index if not exists image_likes_key_idx on public.image_likes (image_key);
create index if not exists image_likes_content_idx on public.image_likes (content_id);
create index if not exists image_likes_created_at_idx on public.image_likes (created_at desc);

do $$
begin
  if not exists (
    select 1
    from pg_catalog.pg_index as index_row
    join pg_catalog.pg_class as index_class on index_class.oid = index_row.indexrelid
    where index_class.relnamespace = 'public'::regnamespace
      and index_class.relname = 'image_likes_user_unique_idx'
      and index_row.indrelid = 'public.image_likes'::regclass
      and index_row.indisunique
      and pg_catalog.pg_get_indexdef(index_row.indexrelid) like '%(image_key, user_id)%'
      and pg_catalog.pg_get_expr(index_row.indpred, index_row.indrelid) = '(user_id IS NOT NULL)'
  ) then
    raise exception 'image_likes_user_unique_idx has an incompatible definition';
  end if;

  if not exists (
    select 1
    from pg_catalog.pg_index as index_row
    join pg_catalog.pg_class as index_class on index_class.oid = index_row.indexrelid
    where index_class.relnamespace = 'public'::regnamespace
      and index_class.relname = 'image_likes_anonymous_unique_idx'
      and index_row.indrelid = 'public.image_likes'::regclass
      and index_row.indisunique
      and pg_catalog.pg_get_indexdef(index_row.indexrelid) like '%(image_key, anonymous_id)%'
      and pg_catalog.pg_get_expr(index_row.indpred, index_row.indrelid) = '(anonymous_id IS NOT NULL)'
  ) then
    raise exception 'image_likes_anonymous_unique_idx has an incompatible definition';
  end if;
end
$$;

alter table public.image_likes enable row level security;
revoke all on table public.image_likes from anon, authenticated;

drop policy if exists "image likes admin read" on public.image_likes;
create policy "image likes admin read"
on public.image_likes
for select
to authenticated
using (public.is_admin());

create or replace function public.get_image_like_summary(
  p_image_keys text[],
  p_anonymous_id uuid default null
)
returns table (
  image_key text,
  like_count bigint,
  liked boolean
)
language plpgsql
stable
security definer
set search_path = pg_catalog, public
as $$
begin
  if coalesce(cardinality(p_image_keys), 0) = 0 then
    return;
  end if;
  if cardinality(p_image_keys) > 100 then
    raise exception 'A maximum of 100 image keys is allowed';
  end if;

  return query
  select
    likes.image_key,
    count(*)::bigint,
    coalesce(bool_or(
      case
        when auth.uid() is not null then likes.user_id = auth.uid()
        else likes.anonymous_id = p_anonymous_id
      end
    ), false)
  from public.image_likes as likes
  where likes.image_key = any(p_image_keys)
  group by likes.image_key;
end;
$$;

revoke all on function public.get_image_like_summary(text[], uuid) from public;
grant execute on function public.get_image_like_summary(text[], uuid) to anon, authenticated;

create or replace function public.toggle_image_like(
  p_content_id uuid,
  p_image_kind text,
  p_image_index integer,
  p_image_key text,
  p_anonymous_id uuid default null
)
returns table (liked boolean, like_count bigint)
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  current_user_id uuid := auth.uid();
  actor_key text;
  target_exists boolean := false;
  removed_count integer := 0;
begin
  if p_content_id is null
    or p_image_kind is null
    or p_image_kind not in ('banner', 'cover', 'detail')
    or p_image_index is null
    or p_image_index < 0
    or p_image_key is null
    or char_length(p_image_key) not between 3 and 2048
    or p_image_key !~ '^[^/?#]+/.+$'
  then
    raise exception 'Invalid image target';
  end if;
  if current_user_id is null and p_anonymous_id is null then
    raise exception 'Anonymous identifier is required';
  end if;

  select exists (
    select 1
    from public.content_management as content
    where content.id = p_content_id
      and (
        (
          p_image_kind = 'banner'
          and content.category::text = 'banner'
          and p_image_index = 0
          and public.nobi_storage_image_key(content.cover_url::text) = p_image_key
        )
        or (
          p_image_kind = 'cover'
          and content.category::text <> 'banner'
          and p_image_index = 0
          and public.nobi_storage_image_key(content.cover_url::text) = p_image_key
        )
        or (
          p_image_kind = 'detail'
          and exists (
            select 1
            from jsonb_array_elements_text(
              case
                when jsonb_typeof(to_jsonb(content.detail_urls)) = 'array' then to_jsonb(content.detail_urls)
                else '[]'::jsonb
              end
            ) with ordinality as detail(image_url, position)
            where detail.position - 1 = p_image_index
              and public.nobi_storage_image_key(detail.image_url) = p_image_key
          )
        )
      )
  ) into target_exists;

  if not target_exists then
    raise exception 'Image target is not part of the current content record';
  end if;

  actor_key := case
    when current_user_id is not null then 'user:' || current_user_id::text
    else 'anonymous:' || p_anonymous_id::text
  end;
  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(actor_key || E'\x1f' || p_image_key, 0)
  );

  if current_user_id is not null then
    delete from public.image_likes as likes
    where likes.image_key = p_image_key
      and likes.user_id = current_user_id;
  else
    delete from public.image_likes as likes
    where likes.image_key = p_image_key
      and likes.anonymous_id = p_anonymous_id;
  end if;
  get diagnostics removed_count = row_count;

  if removed_count = 0 then
    insert into public.image_likes (
      image_key,
      content_id,
      image_kind,
      image_index,
      user_id,
      anonymous_id
    )
    values (
      p_image_key,
      p_content_id,
      p_image_kind,
      p_image_index,
      current_user_id,
      case when current_user_id is null then p_anonymous_id else null end
    );
  end if;

  return query
  select
    removed_count = 0,
    count(*)::bigint
  from public.image_likes as likes
  where likes.image_key = p_image_key;
end;
$$;

revoke all on function public.toggle_image_like(uuid, text, integer, text, uuid) from public;
grant execute on function public.toggle_image_like(uuid, text, integer, text, uuid) to anon, authenticated;

create or replace function public.get_admin_dashboard_stats()
returns jsonb
language plpgsql
stable
security definer
set search_path = pg_catalog, public
as $$
declare
  result jsonb;
begin
  if not public.is_admin() then
    raise exception 'Administrator access required';
  end if;

  select jsonb_build_object(
    'total_views', (select count(*) from public.page_views),
    'today_views', (
      select count(*)
      from public.page_views
      where viewed_on = (pg_catalog.now() at time zone 'Asia/Shanghai')::date
    ),
    'total_posts', (select count(*) from public.posts where parent_id is null),
    'post_likes', (select count(*) from public.post_likes),
    'image_likes', (select count(*) from public.image_likes),
    'views_7d', coalesce((
      select jsonb_agg(day_row order by day_row->>'day')
      from (
        select jsonb_build_object(
          'day', day::date,
          'views', count(page_views.id),
          'visitors', count(distinct page_views.visitor_id)
        ) as day_row
        from generate_series(
          (pg_catalog.now() at time zone 'Asia/Shanghai')::date - 6,
          (pg_catalog.now() at time zone 'Asia/Shanghai')::date,
          interval '1 day'
        ) as day
        left join public.page_views on page_views.viewed_on = day::date
        group by day
      ) as daily
    ), '[]'::jsonb),
    'popular_images', coalesce((
      select jsonb_agg(popular order by (popular->>'likes')::bigint desc)
      from (
        select jsonb_build_object(
          'image_key', likes.image_key,
          'content_id', max(likes.content_id::text),
          'title', max(content.title),
          'image_kind', max(likes.image_kind),
          'image_index', max(likes.image_index),
          'likes', count(*)
        ) as popular
        from public.image_likes as likes
        join public.content_management as content on content.id = likes.content_id
        group by likes.image_key
        order by count(*) desc
        limit 5
      ) as ranked
    ), '[]'::jsonb)
  ) into result;

  return result;
end;
$$;

revoke all on function public.get_admin_dashboard_stats() from public;
grant execute on function public.get_admin_dashboard_stats() to authenticated;

-- The primary key (post_id, user_id) already supports post_id-leading lookups.
-- Add a user_id-leading index only when no equivalent plain index already exists.
do $$
begin
  if not exists (
    select 1
    from pg_catalog.pg_index as index_row
    join pg_catalog.pg_attribute as attribute
      on attribute.attrelid = index_row.indrelid
      and attribute.attname = 'user_id'
    where index_row.indrelid = 'public.post_likes'::regclass
      and index_row.indpred is null
      and index_row.indexprs is null
      and index_row.indnkeyatts = 1
      and index_row.indkey[0] = attribute.attnum
  ) then
    create index post_likes_user_id_idx on public.post_likes (user_id);
  end if;
end
$$;

-- The production preflight must confirm that site_config.section is unique.
-- Existing operational values are never updated by a migration rerun.
insert into public.site_config (section, url)
select 'features_v2', '{"analytics":true,"imageLikes":true}'
where not exists (
  select 1
  from public.site_config as config
  where config.section = 'features_v2'
);

commit;
