-- NOBI 动漫 V2: privacy-conscious page views, persistent image likes and admin metrics.
begin;

-- Align admin checks with the currently deployed users table used by admin.html.
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce((select is_admin from public.users where id = auth.uid()), false)
$$;
revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

create table if not exists public.page_views (
  id bigint generated by default as identity primary key,
  session_id uuid not null,
  visitor_id uuid not null,
  page_path text not null check (char_length(page_path) between 1 and 200 and page_path like '/%'),
  viewed_at timestamptz not null default now(),
  viewed_on date not null default ((now() at time zone 'Asia/Shanghai')::date)
);

create index if not exists page_views_viewed_at_idx on public.page_views (viewed_at desc);
create index if not exists page_views_viewed_on_visitor_idx on public.page_views (viewed_on, visitor_id);

alter table public.page_views enable row level security;
revoke all on table public.page_views from anon, authenticated;

drop policy if exists "page views admin read" on public.page_views;
create policy "page views admin read"
on public.page_views
for select
to authenticated
using (public.is_admin());

create or replace function public.record_page_view(
  p_session_id uuid,
  p_visitor_id uuid,
  p_page_path text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_session_id is null or p_visitor_id is null then
    raise exception 'Anonymous identifiers are required';
  end if;
  if p_page_path is null or char_length(p_page_path) not between 1 and 200 or p_page_path not like '/%' then
    raise exception 'Invalid page path';
  end if;

  if exists (
    select 1
    from public.page_views
    where session_id = p_session_id
      and page_path = split_part(p_page_path, '?', 1)
      and viewed_at > now() - interval '5 seconds'
  ) then
    return;
  end if;

  insert into public.page_views (session_id, visitor_id, page_path)
  values (p_session_id, p_visitor_id, split_part(p_page_path, '?', 1));
end;
$$;

revoke all on function public.record_page_view(uuid, uuid, text) from public;
grant execute on function public.record_page_view(uuid, uuid, text) to anon, authenticated;

create table if not exists public.image_likes (
  id bigint generated by default as identity primary key,
  content_id uuid not null references public.content_management(id) on delete cascade,
  image_kind text not null check (image_kind in ('banner', 'cover', 'detail')),
  image_index integer not null default 0 check (image_index >= 0),
  user_id uuid references auth.users(id) on delete cascade,
  anonymous_id uuid,
  created_at timestamptz not null default now(),
  constraint image_likes_one_actor check (
    (user_id is not null and anonymous_id is null)
    or (user_id is null and anonymous_id is not null)
  )
);

create unique index if not exists image_likes_user_unique_idx
  on public.image_likes (content_id, image_kind, image_index, user_id)
  where user_id is not null;
create unique index if not exists image_likes_anonymous_unique_idx
  on public.image_likes (content_id, image_kind, image_index, anonymous_id)
  where anonymous_id is not null;
create index if not exists image_likes_target_idx
  on public.image_likes (content_id, image_kind, image_index);
create index if not exists image_likes_created_at_idx
  on public.image_likes (created_at desc);

alter table public.image_likes enable row level security;
revoke all on table public.image_likes from anon, authenticated;

drop policy if exists "image likes admin read" on public.image_likes;
create policy "image likes admin read"
on public.image_likes
for select
to authenticated
using (public.is_admin());

create or replace function public.get_image_like_summary(
  p_content_ids uuid[],
  p_anonymous_id uuid default null
)
returns table (
  content_id uuid,
  image_kind text,
  image_index integer,
  like_count bigint,
  liked boolean
)
language sql
stable
security definer
set search_path = public
as $$
  select
    likes.content_id,
    likes.image_kind,
    likes.image_index,
    count(*)::bigint as like_count,
    bool_or(
      case
        when auth.uid() is not null then likes.user_id = auth.uid()
        else likes.anonymous_id = p_anonymous_id
      end
    ) as liked
  from public.image_likes as likes
  where likes.content_id = any(coalesce(p_content_ids, array[]::uuid[]))
  group by likes.content_id, likes.image_kind, likes.image_index;
$$;

revoke all on function public.get_image_like_summary(uuid[], uuid) from public;
grant execute on function public.get_image_like_summary(uuid[], uuid) to anon, authenticated;

create or replace function public.toggle_image_like(
  p_content_id uuid,
  p_image_kind text,
  p_image_index integer,
  p_anonymous_id uuid default null
)
returns table (liked boolean, like_count bigint)
language plpgsql
security definer
set search_path = public
as $$
declare
  current_user_id uuid := auth.uid();
  removed_count integer := 0;
begin
  if p_image_kind not in ('banner', 'cover', 'detail') or p_image_index < 0 then
    raise exception 'Invalid image target';
  end if;
  if not exists (select 1 from public.content_management where id = p_content_id) then
    raise exception 'Content target not found';
  end if;
  if current_user_id is null and p_anonymous_id is null then
    raise exception 'Anonymous identifier is required';
  end if;

  if current_user_id is not null then
    delete from public.image_likes
    where content_id = p_content_id
      and image_kind = p_image_kind
      and image_index = p_image_index
      and user_id = current_user_id;
  else
    delete from public.image_likes
    where content_id = p_content_id
      and image_kind = p_image_kind
      and image_index = p_image_index
      and anonymous_id = p_anonymous_id;
  end if;
  get diagnostics removed_count = row_count;

  if removed_count = 0 then
    insert into public.image_likes (content_id, image_kind, image_index, user_id, anonymous_id)
    values (
      p_content_id,
      p_image_kind,
      p_image_index,
      current_user_id,
      case when current_user_id is null then p_anonymous_id else null end
    );
  end if;

  return query
  select
    removed_count = 0,
    count(*)::bigint
  from public.image_likes
  where content_id = p_content_id
    and image_kind = p_image_kind
    and image_index = p_image_index;
end;
$$;

revoke all on function public.toggle_image_like(uuid, text, integer, uuid) from public;
grant execute on function public.toggle_image_like(uuid, text, integer, uuid) to anon, authenticated;

create or replace function public.get_admin_dashboard_stats()
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  result jsonb;
begin
  if not public.is_admin() then
    raise exception 'Administrator access required';
  end if;

  select jsonb_build_object(
    'total_views', (select count(*) from public.page_views),
    'today_views', (select count(*) from public.page_views where viewed_on = (now() at time zone 'Asia/Shanghai')::date),
    'total_posts', (select count(*) from public.posts where parent_id is null),
    'post_likes', (select count(*) from public.post_likes),
    'image_likes', (select count(*) from public.image_likes),
    'views_7d', coalesce((
      select jsonb_agg(day_row order by day_row->>'day')
      from (
        select jsonb_build_object(
          'day', day::date,
          'views', count(page_views.id),
          'visitors', count(distinct page_views.visitor_id)
        ) as day_row
        from generate_series(
          (now() at time zone 'Asia/Shanghai')::date - 6,
          (now() at time zone 'Asia/Shanghai')::date,
          interval '1 day'
        ) as day
        left join public.page_views on page_views.viewed_on = day::date
        group by day
      ) as daily
    ), '[]'::jsonb),
    'popular_images', coalesce((
      select jsonb_agg(popular order by (popular->>'likes')::bigint desc)
      from (
        select jsonb_build_object(
          'content_id', likes.content_id,
          'title', max(content.title),
          'image_kind', likes.image_kind,
          'image_index', likes.image_index,
          'likes', count(*)
        ) as popular
        from public.image_likes as likes
        join public.content_management as content on content.id = likes.content_id
        group by likes.content_id, likes.image_kind, likes.image_index
        order by count(*) desc
        limit 5
      ) as ranked
    ), '[]'::jsonb)
  ) into result;

  return result;
end;
$$;

revoke all on function public.get_admin_dashboard_stats() from public;
grant execute on function public.get_admin_dashboard_stats() to authenticated;

create index if not exists post_likes_post_id_idx on public.post_likes (post_id);
create index if not exists post_likes_user_id_idx on public.post_likes (user_id);

insert into public.site_config (section, url)
values ('features_v2', '{"analytics":true,"imageLikes":true}')
on conflict (section) do update
set url = excluded.url,
    updated_at = now();

commit;
