-- NOBI Phase 4 trust, safety and account-deletion request workflow.
-- Review and run through the Supabase migration pipeline as the database owner.
-- This file is not applied automatically by the static-site or mobile builds.
begin;

do $$
begin
  if pg_catalog.to_regprocedure('public.is_admin()') is null then
    raise exception 'public.is_admin() security baseline is required';
  end if;
  if pg_catalog.to_regclass('public.posts') is null or pg_catalog.to_regclass('public.profiles') is null then
    raise exception 'Community tables are required';
  end if;
end;
$$;

alter table public.posts
  add column if not exists moderation_status text not null default 'visible',
  add column if not exists moderated_at timestamptz,
  add column if not exists moderated_by uuid references auth.users(id) on delete set null;

alter table public.posts drop constraint if exists posts_moderation_status_check;
alter table public.posts
  add constraint posts_moderation_status_check
  check (moderation_status in ('visible', 'hidden', 'removed'));

create table if not exists public.user_blocks (
  blocker_id uuid not null references auth.users(id) on delete cascade,
  blocked_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (blocker_id, blocked_id),
  constraint user_blocks_not_self check (blocker_id <> blocked_id)
);

create table if not exists public.post_reports (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  reporter_id uuid not null references auth.users(id) on delete cascade,
  reason text not null,
  details text,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid references auth.users(id) on delete set null,
  resolution_note text,
  constraint post_reports_reason_check check (reason in ('spam', 'harassment', 'hate', 'sexual', 'violence', 'privacy', 'other')),
  constraint post_reports_details_length check (details is null or char_length(details) <= 500),
  constraint post_reports_status_check check (status in ('pending', 'reviewing', 'resolved', 'dismissed')),
  constraint post_reports_resolution_note_length check (resolution_note is null or char_length(resolution_note) <= 1000)
);

create unique index if not exists post_reports_one_pending_per_actor_idx
  on public.post_reports (post_id, reporter_id)
  where status in ('pending', 'reviewing');
create index if not exists post_reports_queue_idx on public.post_reports (status, created_at);

create table if not exists public.moderation_actions (
  id bigint generated by default as identity primary key,
  report_id bigint references public.post_reports(id) on delete set null,
  post_id bigint not null references public.posts(id) on delete cascade,
  moderator_id uuid not null references auth.users(id) on delete restrict,
  action text not null,
  note text,
  created_at timestamptz not null default now(),
  constraint moderation_actions_action_check check (action in ('dismiss', 'hide', 'remove', 'restore')),
  constraint moderation_actions_note_length check (note is null or char_length(note) <= 1000)
);

create index if not exists moderation_actions_post_idx on public.moderation_actions (post_id, created_at desc);

create table if not exists public.account_deletion_requests (
  user_id uuid primary key,
  status text not null default 'requested',
  requested_at timestamptz not null default now(),
  cancelled_at timestamptz,
  completed_at timestamptz,
  processing_note text,
  constraint account_deletion_status_check check (status in ('requested', 'processing', 'cancelled', 'completed')),
  constraint account_deletion_note_length check (processing_note is null or char_length(processing_note) <= 1000)
);

alter table public.user_blocks enable row level security;
alter table public.post_reports enable row level security;
alter table public.moderation_actions enable row level security;
alter table public.account_deletion_requests enable row level security;

revoke all on table public.user_blocks, public.post_reports, public.moderation_actions, public.account_deletion_requests from public, anon, authenticated;
grant select on table public.user_blocks, public.post_reports, public.account_deletion_requests to authenticated;
grant select on table public.moderation_actions to authenticated;

drop policy if exists "blocks owner read" on public.user_blocks;
create policy "blocks owner read" on public.user_blocks for select to authenticated
using (blocker_id = auth.uid() or public.is_admin());

drop policy if exists "reports owner or admin read" on public.post_reports;
create policy "reports owner or admin read" on public.post_reports for select to authenticated
using (reporter_id = auth.uid() or public.is_admin());

drop policy if exists "moderation admin read" on public.moderation_actions;
create policy "moderation admin read" on public.moderation_actions for select to authenticated
using (public.is_admin());

drop policy if exists "deletion request owner or admin read" on public.account_deletion_requests;
create policy "deletion request owner or admin read" on public.account_deletion_requests for select to authenticated
using (user_id = auth.uid() or public.is_admin());

drop policy if exists "posts public read" on public.posts;
create policy "posts visible read" on public.posts for select
using (
  user_id = auth.uid()
  or public.is_admin()
  or (
    moderation_status = 'visible'
    and (
      auth.uid() is null
      or user_id is null
      or not exists (
        select 1 from public.user_blocks
        where blocker_id = auth.uid() and blocked_id = posts.user_id
      )
    )
  )
);

-- Prevent post owners from changing identity, hierarchy or moderation columns.
revoke insert, update on table public.posts from authenticated;
grant insert (user_id, content, nickname, avatar_url, title, category, parent_id) on table public.posts to authenticated;
grant update (content, nickname, avatar_url, title, category) on table public.posts to authenticated;

create or replace function public.report_post(p_post_id bigint, p_reason text, p_details text default null)
returns bigint
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  current_user_id uuid := auth.uid();
  report_id bigint;
begin
  if current_user_id is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;
  if p_reason is null or p_reason not in ('spam', 'harassment', 'hate', 'sexual', 'violence', 'privacy', 'other') then
    raise exception 'Invalid report reason' using errcode = '22023';
  end if;
  if p_details is not null and char_length(btrim(p_details)) > 500 then
    raise exception 'Report details are too long' using errcode = '22023';
  end if;
  if not exists (
    select 1 from public.posts
    where id = p_post_id and moderation_status = 'visible' and user_id is distinct from current_user_id
  ) then
    raise exception 'Post is unavailable for reporting' using errcode = 'P0002';
  end if;

  insert into public.post_reports (post_id, reporter_id, reason, details)
  values (p_post_id, current_user_id, p_reason, nullif(btrim(p_details), ''))
  on conflict (post_id, reporter_id) where status in ('pending', 'reviewing')
  do update set reason = excluded.reason, details = excluded.details, created_at = now()
  returning id into report_id;
  return report_id;
end;
$$;

create or replace function public.set_user_block(p_blocked_id uuid, p_blocked boolean default true)
returns boolean
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  current_user_id uuid := auth.uid();
begin
  if current_user_id is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;
  if p_blocked_id is null or p_blocked is null or p_blocked_id = current_user_id then
    raise exception 'Invalid blocked user' using errcode = '22023';
  end if;
  if not exists (select 1 from auth.users where id = p_blocked_id) then
    raise exception 'User not found' using errcode = 'P0002';
  end if;

  if p_blocked then
    insert into public.user_blocks (blocker_id, blocked_id)
    values (current_user_id, p_blocked_id)
    on conflict (blocker_id, blocked_id) do nothing;
  else
    delete from public.user_blocks where blocker_id = current_user_id and blocked_id = p_blocked_id;
  end if;
  return p_blocked;
end;
$$;

create or replace function public.request_account_deletion()
returns timestamptz
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  current_user_id uuid := auth.uid();
  requested timestamptz := now();
begin
  if current_user_id is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;
  insert into public.account_deletion_requests (user_id, status, requested_at, cancelled_at, completed_at, processing_note)
  values (current_user_id, 'requested', requested, null, null, null)
  on conflict (user_id) do update
  set status = 'requested', requested_at = excluded.requested_at, cancelled_at = null, completed_at = null, processing_note = null;
  return requested;
end;
$$;

create or replace function public.cancel_account_deletion_request()
returns boolean
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  current_user_id uuid := auth.uid();
begin
  if current_user_id is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;
  update public.account_deletion_requests
  set status = 'cancelled', cancelled_at = now()
  where user_id = current_user_id and status = 'requested';
  return found;
end;
$$;

create or replace function public.review_post_report(p_report_id bigint, p_action text, p_note text default null)
returns void
language plpgsql
security definer
set search_path = pg_catalog
as $$
declare
  moderator uuid := auth.uid();
  target_post bigint;
begin
  if moderator is null or not public.is_admin() then
    raise exception 'Administrator access required' using errcode = '42501';
  end if;
  if p_action is null or p_action not in ('dismiss', 'hide', 'remove', 'restore') then
    raise exception 'Invalid moderation action' using errcode = '22023';
  end if;
  if p_note is not null and char_length(btrim(p_note)) > 1000 then
    raise exception 'Moderation note is too long' using errcode = '22023';
  end if;

  select post_id into target_post from public.post_reports where id = p_report_id for update;
  if target_post is null then
    raise exception 'Report not found' using errcode = 'P0002';
  end if;

  if p_action = 'hide' then
    update public.posts set moderation_status = 'hidden', moderated_at = now(), moderated_by = moderator where id = target_post;
  elsif p_action = 'remove' then
    update public.posts set moderation_status = 'removed', moderated_at = now(), moderated_by = moderator where id = target_post;
  elsif p_action = 'restore' then
    update public.posts set moderation_status = 'visible', moderated_at = now(), moderated_by = moderator where id = target_post;
  end if;

  update public.post_reports
  set status = case when p_action = 'dismiss' then 'dismissed' else 'resolved' end,
      reviewed_at = now(), reviewed_by = moderator, resolution_note = nullif(btrim(p_note), '')
  where id = p_report_id;

  insert into public.moderation_actions (report_id, post_id, moderator_id, action, note)
  values (p_report_id, target_post, moderator, p_action, nullif(btrim(p_note), ''));
end;
$$;

revoke all on function public.report_post(bigint, text, text) from public, anon, authenticated;
revoke all on function public.set_user_block(uuid, boolean) from public, anon, authenticated;
revoke all on function public.request_account_deletion() from public, anon, authenticated;
revoke all on function public.cancel_account_deletion_request() from public, anon, authenticated;
revoke all on function public.review_post_report(bigint, text, text) from public, anon, authenticated;
grant execute on function public.report_post(bigint, text, text) to authenticated;
grant execute on function public.set_user_block(uuid, boolean) to authenticated;
grant execute on function public.request_account_deletion() to authenticated;
grant execute on function public.cancel_account_deletion_request() to authenticated;
grant execute on function public.review_post_report(bigint, text, text) to authenticated;

commit;
